name: Liquibase Migration
 
on:
  workflow_dispatch:
    inputs:
      base_path:
        description: "Base path in releasemanagement branch (e.g., Release/2305)"
        required: true
        type: string

env:
  TARGET_REPO: "git-ci-123/NAAP_PROJECT"
  PROPERTIES_BRANCH: "dev-properties"
  RELEASE_BRANCH: "releasemanagement"
  MANIFEST_BRANCH: "dev-manifest"
  SCRIPT_BRANCH: "dev-script"

jobs:
  liquibase-migration:
    runs-on: naap
    steps:
      - name: Checkout CICD Repository 
        uses: actions/checkout@v4

      - name: Checkout Release Repository
        uses: actions/checkout@v4
        with:
          repository:  ${{ env.TARGET_REPO }}
          token: ${{ secrets.PAT_TOKEN }}    
          ref: ${{ env.RELEASE_BRANCH }}
          path: 'NAAP_Release' 
 
      - name: Validate Base Path in Releasemanagement Branch
        run: |
          pwd
          ls
          BASE_PATH="${{ github.event.inputs.base_path }}"
          if [ ! -d NAAP_Release/"$BASE_PATH" ]; then
            echo "❌ Error: Base path $BASE_PATH not found!"
            exit 1
          fi
          echo "BASE_PATH=NAAP_Release/$BASE_PATH" >> $GITHUB_ENV
          echo "✅ Base path NAAP_Release/$BASE_PATH found."
 
      - name: Extract Release Folder from [DB] in input.txt
        id: read_input
        run: |
          RELEASE_FOLDER=$(sed -n '/^\[DB\]/ {n; p;}' "$BASE_PATH/input.txt" | tr -d '\r')
          if [ -z "$RELEASE_FOLDER" ]; then
            echo "❌ Error: Could not extract release folder!"
            exit 1
          fi
          echo "RELEASE_FOLDER=$RELEASE_FOLDER" >> $GITHUB_ENV
          echo "✅ Extracted release folder: $RELEASE_FOLDER."
 
      - name: Checkout DB Scripts (db-scripts branch)
        uses: actions/checkout@v4
        with:
          repository:  ${{ env.TARGET_REPO }}
          token: ${{ secrets.PAT_TOKEN }}    
          ref: ${{ env.SCRIPT_BRANCH }}
          path: 'NAAP_DB'
 
      - name: Validate Release Folder in DB Scripts Branch
        run: |
          DB_SCRIPTS_PATH="NAAP_DB/$RELEASE_FOLDER"
          if [ ! -d "$DB_SCRIPTS_PATH" ]; then
            echo "❌ Error: Release folder $RELEASE_FOLDER not found in db-scripts branch!"
            exit 1
          fi
          echo "✅ Release folder $RELEASE_FOLDER found in db-scripts branch."
 
      - name: Execute Liquibase Scripts for Multiple Schemas
        env:
          LIQUIBASE_COMMAND_URL: ${{ secrets.DB_DEV_URL }}
          DB_USER_APPCATALOG: ${{ secrets.APPCATALOG_DEV_USER }}
          DB_PASSWORD_APPCATALOG: ${{ secrets.APPCATALOG_DEV_PASSWD }}
          DB_USER_BACATALOG: ${{ secrets.BACATALOG_DEV_USER }}
          DB_PASSWORD_BACATALOG: ${{ secrets.BACATALOG_DEV_PASSWD }}
          DB_USER_CATALOG: ${{ secrets.CATALOG_DEV_USER }}
          DB_PASSWORD_CATALOG: ${{ secrets.CATALOG_DEV_PASSWD }}
        run: |
          RELEASE_PATH="NAAP_DB/$RELEASE_FOLDER"
          echo "🚀 Processing release: $RELEASE_FOLDER"

          # Iterate over each schema folder (e.g., 08_APPCATALOG, 09_BACATALOG)
          find "$RELEASE_PATH" -maxdepth 1 -mindepth 1 -type d | sort | while read -r schema_folder; do
            SCHEMA_FULL_NAME=$(basename "$schema_folder")
            SCHEMA_NAME=$(echo "$SCHEMA_FULL_NAME" | cut -d'_' -f2)  # Extract schema name after "_"

            # Fetch credentials dynamically based on extracted schema name
            SCHEMA_USER_VAR="DB_USER_${SCHEMA_NAME}"
            SCHEMA_PASS_VAR="DB_PASSWORD_${SCHEMA_NAME}"

            # Get the value from preloaded env variables
            SCHEMA_USER="${!SCHEMA_USER_VAR}"
            SCHEMA_PASS="${!SCHEMA_PASS_VAR}"

            # Validate if credentials exist
            if [ -z "$SCHEMA_USER" ]; then
              echo "⚠️ Warning: User credential not found for schema $SCHEMA_NAME. Skipping schema..."
              continue
            fi
            if [ -z "$SCHEMA_PASS" ]; then
              echo "⚠️ Warning: Password credential not found for schema $SCHEMA_NAME. Skipping schema..."
              continue
            fi

            echo "✅ Found credentials for schema: $SCHEMA_NAME"

            # Iterate through subfolders and apply scripts
            find "$schema_folder" -type d | sort | while read -r subfolder; do
              echo "📁 Executing in: $subfolder"
              find "$subfolder" -type f -name "*.sql" | sort | while read -r script; do
                echo "📝 Running $script"
                if ! liquibase --url="$LIQUIBASE_COMMAND_URL" --username="$SCHEMA_USER" --password="$SCHEMA_PASS" \
                  --changeLogFile="$script" update; then
                  echo "❌ Error running $script for $SCHEMA_NAME!"
                  exit 1
                fi
              done
            done
          done
