name: Cleanslate Execution

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release Path"
        required: true
        type: string

jobs:
  checkout:
    runs-on: naap
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Checkout Project Repository
        uses: actions/checkout@v2
        with:
          repository: 'git-ci-123/NAAP_PROJECT'
          token: ${{ secrets.GITHUB_TOKEN }}    
          ref: releasemanagement
          path: 'NAAP_Release'

      - name: Check RDS Instance Connection
        run: |
          sudo apt-get update && sudo apt-get install -y telnet
          if telnet naapdev.cric42eckumc.us-east-2.rds.amazonaws.com 1521; then
            echo "Connection successful!"
          else
            echo "Connection failed!"
            exit 1
          fi
