name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release Path"
        required: true
        type: string
        
jobs:
  File-Extension-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Checkout the other repository
        uses: actions/checkout@v2
        with:
          repository: 'git-ci-123/NAAP_PROJECT'
          token: ${{ secrets.GITHUB_TOKEN }}    
          path: 'NAAP_PROJECT'
          
      - name: Check if the file has a .properties extension
        run: |
          FILE_PATH="${{ github.event.inputs.file_path }}"

          if [[ -f "NAAP_PROJECT/$FILE_PATH" && "$FILE_PATH" == *.properties ]]; then
            echo "Valid .properties file"
          elif [[ ! -f "NAAP_PROJECT/$FILE_PATH" ]]; then
            echo "File does not exist at the given path"
            exit 1
          else
            echo "Invalid file type. The file does not have a .properties extension."
            exit 1
          fi

