name: Consolidated Workflow - try

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release Path"
        required: true
        type: string

env:
  TARGET_REPO: "git-ci-123/NAAP_PROJECT"  # Change to your actual repo.
  PROPERTIES_BRANCH: "dev-properties"     # Branch where property files are stored.
  RELEASE_BRANCH: "releasemanagement"     # Branch where the release folder is stored.
  MANIFEST_BRANCH: "dev-manifest"         # Branch where the manifest files are stored.
  SCRIPT_BRANCH: "dev-script"             # Branch where the DB scripts are stored.

jobs:
  Email-Notification:
    runs-on: ubuntu-latest
    
    if: always()
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mx-02-us-east-2.prod.hydra.sophos.com
          server_port: 25
          username: "krishnakumar.s@excelacom.in"
          password: "${{ secrets.MAIL_PASSWORD }}"
          subject: "CI/CD Pipeline - ${{ job.status }}"
          body: |
            Hi
            
          to: "sundaran.n@excelacom.in"
          from: "krishnakumar.s@excelacom.in"

