name: Send Email Notification

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mx-02-us-east-2.prod.hydra.sophos.com
          server_port: 25
          username: "Sundaran.N@excelacom.in"
          password: "${{ secrets.MAIL_PASSWORD }}"
          subject: "CI/CD Pipeline"
          body: |
           Hi, just a check for email.
          to: "KrishnaKumar.S@excelacom.in"
          from: "Sundaran.N@excelacom.in"


   
