name: Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send email notification via SMTP
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: githubactionstest1@gmail.com
        password: DevopsAdmin@123
        subject: "GitHub Actions Email Test"
        body: "Hello! This email was sent from a GitHub Actions workflow."
        to: "sundaran.n@excelacom.in"
        from: "githubactionstest1@gmail.com"
        secure: true

    
