name: Email





on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          
          subject: "Test Email from GitHub Actions"
          to: sundaran.n@excelacom.in
          from: githubactionstest1@gmail.com
          body: "GitHub Actions test."
          secure: true

  
  
